default_platform(:android)

platform :android do
  desc "Upload Android beta to Google Play internal track"
  lane :beta do
    upload_to_play_store(
      track: "internal",
      aab: ENV["AAB_PATH"] || "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: "draft"
    )
  end

  desc "Upload Android production release to Google Play production track"
  lane :production do
    upload_to_play_store(
      track: "production",
      aab: ENV["AAB_PATH"] || "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: "completed"
    )
  end
end
